# Generated by Django 2.2 on 2019-12-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], editable=False, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_file',
            field=models.FileField(upload_to='api/uploads/'),
        ),
    ]
