# Generated by Django 2.2 on 2020-01-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacedRepetitionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='srcs.SectionItem')),
            ],
        ),
    ]
